import './globals.css'
import type { Metadata } from 'next'
import { Poppins, Lato } from 'next/font/google'
import SocketProvider from '@/context/socket-context'

const lato = Lato({ subsets: ['latin'], weight: ['300', '400', '700'], variable: '--font-lato' })
const poppins = Poppins({ subsets: ['latin'], weight: ['300', '400', '600', '700'], variable: '--font-poppins' })

export const metadata: Metadata = {
   title: "What's up Website",
   description: 'Generated by create next app',
   icons: {
      // Public path
      icon: '/favicon.png',
   },
}

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode
}>) {
   return (
      <html lang="en" className={`${lato.variable} ${poppins.variable}`}>
         <body>
            <SocketProvider>{children}</SocketProvider>
         </body>
      </html>
   )
}
